language: ruby

rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.1

env:
  - TEST_WITH_RACK=1.4.0
  - TEST_WITH_RACK=1.5.0
  - TEST_WITH_RACK=1.6.0
  - TEST_WITH_RACK=2.0.0

script: bundle exec rake spec features
