language: ruby

rvm:
  - 1.8
  - 1.9
  - 2.0
  - 2.1

env:
  - TEST_WITH_RACK=1.1.0
  - TEST_WITH_RACK=1.2.0
  - TEST_WITH_RACK=1.3.0
  - TEST_WITH_RACK=1.4.0
  - TEST_WITH_RACK=1.5.0
  - TEST_WITH_RACK=1.6.0

script: bundle exec rake spec features
