sudo: false

language: ruby

rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1

env:
  - TEST_WITH_RACK=1.4.0
  - TEST_WITH_RACK=1.5.0
  - TEST_WITH_RACK=1.6.0
  - TEST_WITH_RACK=2.0.0

script: bundle exec rake spec features
